---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: test-oc-plugin
    app.kubernetes.io/name: test-oc-plugin
    rht-gitops.com/janus-argocd: test-oc-plugin
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: test-oc-plugin
    app.kubernetes.io/name: test-oc-plugin
    rht-gitops.com/janus-argocd: test-oc-plugin
  name: storeuseradmin-sa
